context:
  version: 1.15.0

package:
  name: diagnostic-languageserver
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/diagnostic-languageserver/-/diagnostic-languageserver-${{ version }}.tgz
  sha256: fe8b6d46b2b713cf87637abd7173d42e9cfce89c1d397b2815be888f12b36c06

build:
  number: 0
  noarch: generic

requirements:
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - diagnostic-languageserver --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: diagnostic language server integrate with linters
  homepage: https://github.com/iamcco/diagnostic-languageserver
  repository: https://github.com/iamcco/diagnostic-languageserver

extra:
  recipe-maintainers:
    - danielnachun
